version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: traffic_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  rstudio:
    build:
      context: .
      dockerfile: Dockerfile.rstudio
    ports:
      - "8787:8787"
    environment:
      PASSWORD: rpassword
    volumes:
      - ./r_model:/home/rstudio/r_model
      - ./.env:/home/rstudio/.env

  shiny:
    build:
      context: .
      dockerfile: Dockerfile.shiny
    ports:
      - "3838:3838"
    volumes:
      - ./shiny_app:/srv/shiny-server